baseURL: "https://theme.scientific-python.org/"
languageCode: "en-us"
title: "Hiperwalk"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: "Python package for simulations of quantum walks on graphs using HPC"
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Hiperwalk
    link: /
  hero:
    title: Hiperwalk
    image: logo.svg
    buttontext: Latest release
    subtitle: Simulations of quantum walks on graphs using HPC
  navbar:
    - title: Get started
      url: /getstarted/
    - title: Documentation
      url: /doc/
    - title: Shortcodes
      url: /shortcodes/
  keyfeatures:
    features:
      - title: Documented
        text: The theme is documented at https://theme.scientific-python.org.
      - title: Reusable
        text: "The theme is being used by
          [scientific-python.org](https://github.com/scientific-python/scientific-python.org),
          [numpy.org](https://github.com/numpy/numpy.org), and
          [scipy.org](https://github.com/scipy/scipy.org)."
      - title: Community Maintained
        text: The theme is maintained by the [Theme Team](/about/).
      - title: Open source
        text: Distributed under [LGPL3](https://github.com/hiperwalk/hiperwalk/blob/master/LICENSE), Hiperwalk is developed and maintained [publicly on GitHub](https://github.com/hiperwalk/hiperwalk).
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://hiperwalk.org/
        icon: scientific-python
      - link: https://discuss.scientific-python.org/
        icon: discourse
      - link: https://github.com/hiperwalk/
        icon: github
    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
          - text: Theme GitHub
            link: https://github.com/scientific-python/scientific-python-hugo-theme
      column2:
        links:
          - text: Scientific Python Forum
            link: https://discuss.scientific-python.org
      column3:
        links:
