baseURL: "https://theme.scientific-python.org/"
languageCode: "en-us"
title: "Hiperwalk"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: "Python package for simulations of quantum walks on graphs using HPC"
  images:
    - /images/logo.png
  navbarlogo:
    image: logo.png
    text: Hiperwalk
    link: /
  hero:
    title: Hiperwalk
    image: logo.png
    buttontext: GitHub
    buttonlink: https://github.com/hiperwalk/hiperwalk/
    subtitle: Simulations of quantum walks on graphs using HPC
  navbar:
    - title: Get started
      url: /docs/
    - title: Install
      url: /docs/install
    - title: Documentation
      url: /docs/documentation/
    - title: Examples
      url: https://github.com/hiperwalk/hiperwalk/tree/master/examples
  keyfeatures:
    features:
      - title: Quantum Walks
        text: Hiperwalk simulates both continuous-time and discrete-time quantum walks, effectively modeling quantum systems on large graphs.
      - title: Heterogeneous HPC
        text: Hiperwalk facilitates quantum walk simulations, leveraging the power of heterogeneous HPC using CPUs, GPUs, and acceleration cards.
      - title: Open source
        text: Distributed under [LGPL3](https://github.com/hiperwalk/hiperwalk/blob/master/LICENSE), Hiperwalk is developed and maintained [publicly on GitHub](https://github.com/hiperwalk/hiperwalk).
  footer:
    logo: logo.png
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/hiperwalk/
        icon: github
    quicklinks:
      column1:
        title: ""
        links:
          - text: About Us
            link: /about/
      column2:
        links:
          - text: Documentation
            link: /docs/
          - text: Tutorial
            link: /docs/tutorial
      column3:
        links:
