name: GitHub Pages

on:                                              
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1                  
      with:
        submodules: true

    - name: Setup Hugo                           
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.109.0'
        extended: true

    - name: Build site
      run: hugo

    - name: Checkout hiperwalk source code
      uses: actions/checkout@v3
      with:
        repository: hiperwalk/hiperwalk
        path: hiperwalk
        ref: 2.0.x

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build docs
      run: |
          pushd hiperwalk/docs/
          pip3 install -r requirements.txt
          ./go
          popd

    - name: Copy Sphinx generated HTML files
      run: |
          mkdir -p ./public/doc
          cp -r hiperwalk/docs/build/html/* ./public/doc

    - name: Prevent Jekyll processing
      run: touch ./public/.nojekyll

    - name: Deploy                               
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
