name: GitHub Pages

on:                                              
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1                  
      with:
        submodules: true

    - name: Setup Hugo                           
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.109.0'
        extended: true

    - name: Build site
      run: hugo

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install graphviz
      run: |
          sudo apt update
          sudo apt install graphviz

    - name: Checkout hiperwalk source code (stable)
      uses: actions/checkout@v3
      with:
        repository: hiperwalk/hiperwalk
        path: hiperwalk
        ref: v2.0a5

    - name: Build docs (stable)
      run: |
          pushd hiperwalk/docs/
          pip3 install -r requirements.txt
          ./go
          popd

    - name: Copy Sphinx generated HTML files (stable)
      run: |
          mkdir -p ./public/docs/stable
          cp -r hiperwalk/docs/build/html/* ./public/docs/stable
          rm -rf hiperwalk

    - name: Checkout hiperwalk source code (latest)
      uses: actions/checkout@v3
      with:
        repository: hiperwalk/hiperwalk
        path: hiperwalk
        ref: master

    - name: Build docs (latest)
      run: |
          pushd hiperwalk/docs/
          pip3 install -r requirements.txt
          ./go
          popd

    - name: Copy Sphinx generated HTML files (latest)
      run: |
          mkdir -p ./public/docs/latest
          cp -r hiperwalk/docs/build/html/* ./public/docs/latest
          rm -rf hiperwalk

    - name: Prevent Jekyll processing
      run: touch ./public/.nojekyll

    - name: Create CNAME
      run: echo 'hiperwalk.org' >  ./public/CNAME

    - name: Deploy                               
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
